WinWaitActive("Sign in")
Send("consiliotest\samada")
send("{TAB}")
send("Global@88821144")
send("{ENTER}")
WinWaitActive("Sign in")
Send("consiliotest\samada")
send("{TAB}")
send("Global@88821144")
send("{ENTER}")