WinWaitActive("Sign in")
Send("consiliotest\samada")
send("{TAB}")
send("Supernova2021!!")
send("{ENTER}")
WinWaitActive("Sign in")
Send("consiliotest\samada")
send("{TAB}")
send("Supernova2021!!")
send("{ENTER}")